### ISSUE TITLE
[Fix] 설정 관련

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [Central-MakeUs/CurtainCall-Server#26]
## Todo

- [x] 로컬 로그인 가능하도록
- [x] 인증 설정 수정
  - 로그인 entrypoint
  - 서버 로그인
~~- [ ] 서버 로그 연결~~
- [x] 한글 깨지는 문제
- [x] s3 설정 확인
- [x] 애플 로그인
