### ISSUE TITLE
[FEATURE] 공연 로직

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [Central-MakeUs/CurtainCall-Server#41]
## Todo

~~- [ ] 공연 리뷰 통계 배치에 영향 안되도록~~
  - 테이블 분리 혹은 낙관 락 고려
  - #13 
- [x] 리뷰 평점 평균을 넣어야 정렬 가능
- [x] 공연 상태
- [x] 마감 임박 공연
- [x] 인기 순위 데이터 없는 경우 대응
  - 데이터 없을 경우 이전 날짜 혹은 있는 것 중 가장 최신 날짜 반환해주도록
