### ISSUE TITLE
[FIX] 이미지 생성

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [Central-MakeUs/CurtainCall-Server#52]
## Todo

- [ ] 이미지 생성 오류
- [x] 파티 생성 오류
- [x] 임시 회원가입 수정
