### ISSUE TITLE
[FEATURE] 문서 nullable

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [Central-MakeUs/CurtainCall-Server#63]
## Todo

- [ ] request body nullable
- [ ] response body nullable
- [ ] schema.sql 칼럼 순서 정리
